(() => {
  const D=window.ATM_DATA,PP=window.ATM_PLAYER_PROFILES||{};if(!D?.clubs)return;
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast=msg=>window.ATMToast?window.ATMToast(msg):console.log(msg),clubs=[...D.clubs].sort((a,b)=>a.name.localeCompare(b.name)),club=id=>clubs.find(c=>c.id===id);
  const groups=[{label:'BACKS',slots:[['BP','Back Pocket'],['FB','Full Back'],['BP2','Back Pocket']]},{label:'HALF BACKS',slots:[['HBF','Half Back Flank'],['CHB','Centre Half Back'],['HBF2','Half Back Flank']]},{label:'CENTRES',slots:[['W','Wing'],['C','Centre'],['W2','Wing']]},{label:'HALF FORWARDS',slots:[['HFF','Half Forward Flank'],['CHF','Centre Half Forward'],['HFF2','Half Forward Flank']]},{label:'FORWARDS',slots:[['FP','Forward Pocket'],['FF','Full Forward'],['FP2','Forward Pocket']]},{label:'FOLLOWERS',slots:[['RUC','Ruck'],['RR','Ruck Rover'],['ROV','Rover']]},{label:'INTERCHANGE',interchange:true,slots:[['INT1','Interchange 1'],['INT2','Interchange 2'],['INT3','Interchange 3'],['INT4','Interchange 4'],['INT5','Interchange 5']]}];
  const slotKeys=groups.flatMap(g=>g.slots.map(x=>x[0])),lineups={},extras={};let clubId='ric';
  const blank=()=>Object.fromEntries(slotKeys.map(k=>[k,''])),lineup=()=>lineups[clubId] ||= blank(),customList=(id=clubId)=>extras[id] ||= [];
  const selectedSet=(except=null)=>new Set(Object.entries(lineup()).filter(([k,v])=>v&&k!==except).map(([,v])=>v));
  function allPlayers(){const m=new Map(club(clubId).players.map(name=>[name,{name,position:'',source:'Club list'}]));customList().forEach(p=>m.set(p.name,p));return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name));}
  const meta=name=>allPlayers().find(p=>p.name===name)||{name,position:'',source:'Club list'};
  function applyTheme(){const c=club(clubId),mode=$('#best23Mode');if(mode){mode.style.setProperty('--club',c.color);mode.style.setProperty('--clubText',c.clubText||'#fff');}}
  function renderClubOptions(){const s=$('#best23Club');if(!s)return;s.innerHTML=clubs.map(c=>`<option value="${c.id}" ${c.id===clubId?'selected':''}>${esc(c.name)}</option>`).join('');s.onchange=()=>{clubId=s.value;render();};}
  function renderIdentity(){const c=club(clubId),el=$('#best23ClubIdentity');if(!el)return;el.innerHTML=`<span class="builder-logo-box"><img src="${esc(c.logo)}" alt="${esc(c.name)} logo"></span><span><strong>${esc(c.name)}</strong><small>${customList().length?`${customList().length} hypothetical player${customList().length!==1?'s':''} added`:'Current club list'}</small></span>`;$('#best23Count').textContent=`${Object.values(lineup()).filter(Boolean).length} / 23`;}
  function options(key){const cur=lineup()[key],used=selectedSet(key);return `<option value="">— SELECT PLAYER —</option>`+allPlayers().map(p=>`<option value="${esc(p.name)}" ${cur===p.name?'selected':''} ${used.has(p.name)?'disabled':''}>${esc(p.name)}${p.source!=='Club list'?` • ${esc(p.source)}`:''}</option>`).join('');}
  function renderField(){const el=$('#best23Field');if(!el)return;el.innerHTML=groups.map(g=>`<div class="field-line ${g.interchange?'interchange':''}"><div class="field-line-label">${esc(g.label)}</div><div class="field-line-slots">${g.slots.map(([key,label])=>{const v=lineup()[key],p=v?meta(v):null;return `<div class="position-slot ${p&&p.source!=='Club list'?'hypothetical':''}"><div class="position-name">${esc(label)}</div><select class="position-select" data-slot="${key}">${options(key)}</select>${p&&p.source!=='Club list'?`<span class="assumption-tag">${esc(p.source)}</span>`:''}</div>`;}).join('')}</div></div>`).join('');document.querySelectorAll('[data-slot]').forEach(s=>s.onchange=()=>{const k=s.dataset.slot,v=s.value;if(v&&selectedSet(k).has(v)){toast(`${v} is already selected`);return renderField();}lineup()[k]=v;render();});}
  function addNext(name){if(Object.values(lineup()).includes(name))return toast(`${name} is already in your 23`);const k=slotKeys.find(x=>!lineup()[x]);if(!k)return toast('Your Best 23 is already full');lineup()[k]=name;render();}
  function renderPool(){const el=$('#best23Pool');if(!el)return;const q=($('#best23Search')?.value||'').toLowerCase().trim(),chosen=new Set(Object.values(lineup()).filter(Boolean));el.innerHTML=allPlayers().filter(p=>(`${p.name} ${p.position} ${p.source}`).toLowerCase().includes(q)).map(p=>`<div class="squad-row ${chosen.has(p.name)?'selected':''} ${p.source!=='Club list'?'hypothetical-row':''}"><div><div class="squad-name">${esc(p.name)}</div><div class="squad-status">${p.position?`${esc(p.position)} • `:''}${chosen.has(p.name)?'Selected in Best 23':esc(p.source)}</div></div><button class="squad-add" data-add-player="${esc(p.name)}" ${chosen.has(p.name)?'disabled':''}>ADD</button></div>`).join('');el.querySelectorAll('[data-add-player]').forEach(b=>b.onclick=()=>addNext(b.dataset.addPlayer));}
  function openModal(html){const m=$('#draftModal'),c=$('#draftModalCard');if(!m||!c)return;c.innerHTML=html;m.hidden=false;} function close(){const m=$('#draftModal'),c=$('#draftModalCard');if(m)m.hidden=true;if(c)c.innerHTML='';}
  function addAny(){openModal(`<div class="modal-kicker">ADD ANY PLAYER</div><h3>Add a player to ${esc(club(clubId).name)}</h3><p>Use this for any trade, draft or hypothetical assumption — e.g. Toby Greene, Arki Butler or anyone else.</p><label class="modal-label">PLAYER NAME</label><input id="customPlayerName" class="modal-input" placeholder="Player name"><label class="modal-label">POSITION / ROLE</label><input id="customPlayerPosition" class="modal-input" placeholder="e.g. Forward / Midfielder"><label class="modal-label">ASSUMPTION</label><select id="customPlayerSource" class="modal-select"><option>Custom assumption</option><option>Trade assumption</option><option>Draft assumption</option></select><div class="modal-actions"><button id="cancelCustomPlayer" class="ghost-btn">CANCEL</button><button id="saveCustomPlayer" class="primary-btn">ADD TO SQUAD</button></div>`);$('#cancelCustomPlayer').onclick=close;$('#saveCustomPlayer').onclick=()=>{const name=$('#customPlayerName').value.trim(),position=$('#customPlayerPosition').value.trim(),source=$('#customPlayerSource').value;if(!name)return toast('Enter a player name');if(allPlayers().some(p=>p.name.toLowerCase()===name.toLowerCase()))return toast(`${name} is already available`);customList().push({name,position,source});close();render();toast(`${name} added to ${club(clubId).name}`);};}
  function addProspect(){const names=Object.keys(PP).sort();openModal(`<div class="modal-kicker">MY DRAFT PROSPECT</div><h3>Add one of your 2026 prospects</h3><p>This list comes from your player-profile board, not a third-party ranking order.</p><select id="myProspect" class="modal-select">${names.map(n=>`<option value="${esc(n)}">${esc(n)} • ${esc(PP[n].position||'')}</option>`).join('')}</select><div class="modal-actions"><button id="cancelMyProspect" class="ghost-btn">CANCEL</button><button id="saveMyProspect" class="primary-btn">ADD PROSPECT</button></div>`);$('#cancelMyProspect').onclick=close;$('#saveMyProspect').onclick=()=>{const name=$('#myProspect').value,p=PP[name];if(allPlayers().some(x=>x.name===name))return toast(`${name} is already available`);customList().push({name,position:p?.position||'',source:'Draft assumption'});close();render();toast(`${name} added as a draft assumption`);};}
  function importTrade(){const incoming=window.TradeMachine?.getIncomingPlayers?.(clubId)||[];if(!incoming.length)return toast(`No incoming traded players for ${club(clubId).name}`);let n=0;incoming.forEach(a=>{if(!allPlayers().some(p=>p.name===a.name)){customList().push({name:a.name,position:'',source:'Trade assumption'});n++;}});render();toast(n?`${n} incoming player${n!==1?'s':''} added`:'Those incoming players are already available');}
  function copyTeam(){const c=club(clubId),lines=[];groups.forEach(g=>lines.push(`${g.label}: ${g.slots.map(([k])=>lineup()[k]||'—').join(', ')}`));navigator.clipboard?.writeText(`${c.name} Best 23\n${lines.join('\n')}`).then(()=>toast('Best 23 copied')).catch(()=>toast('Copy unavailable'));}
  function clearTeam(){lineups[clubId]=blank();render();toast(`${club(clubId).name} team cleared`);}
  function render(){applyTheme();renderClubOptions();renderIdentity();renderField();renderPool();}
  function init(){if($('#best23Search'))$('#best23Search').oninput=renderPool;if($('#copyBest23Btn'))$('#copyBest23Btn').onclick=copyTeam;if($('#resetBest23Btn'))$('#resetBest23Btn').onclick=clearTeam;if($('#addBest23PlayerBtn'))$('#addBest23PlayerBtn').onclick=addAny;if($('#importTradePlayersBtn'))$('#importTradePlayersBtn').onclick=importTrade;if($('#addDraftProspectBtn'))$('#addDraftProspectBtn').onclick=addProspect;render();}
  window.Best23={render,clear:clearTeam};init();
})();