window.ATM_DATA = {
  updated: 'After Round 23 • 18 Aug 2026',
  clubs: [
    {id:'fre',name:'Fremantle',abbr:'FRE',color:'#5b2b82',rank:1,players:['Caleb Serong','Andrew Brayshaw','Luke Jackson','Shai Bolton','Sean Darcy','Hayden Young','Josh Treacy','Alex Pearce','Jordan Clark','Luke Ryan','Jye Amiss','Murphy Reid']},
    {id:'syd',name:'Sydney',abbr:'SYD',color:'#e31b23',rank:2,players:['Chad Warner','Isaac Heeney','Errol Gulden','Charlie Curnow','Tom Papley','Brodie Grundy','Callum Mills','Nick Blakey','Tom McCartin','Logan McDonald','James Rowbottom','Matt Roberts']},
    {id:'bri',name:'Brisbane',abbr:'BRI',color:'#7b002c',rank:3,players:['Will Ashcroft','Hugh McCluggage','Josh Dunkley','Harris Andrews','Lachie Neale','Zac Bailey','Cam Rayner','Charlie Cameron','Oscar Allen','Darcy Wilmot','Kai Lohmann','Levi Ashcroft']},
    {id:'gee',name:'Geelong',abbr:'GEE',color:'#002b5c',rank:6,players:['Max Holmes','Bailey Smith','Jeremy Cameron','Connor O\'Sullivan','Tom Stewart','Gryan Miers','Sam De Koning','Tyson Stengle','Oliver Dempsey','Patrick Dangerfield','James Worpel','Jack Bowes']},
    {id:'mel',name:'Melbourne',abbr:'MEL',color:'#061a33',rank:5,players:['Max Gawn','Kysaiah Pickett','Jack Viney','Jack Steele','Jake Lever','Steven May','Trent Rivers','Jacob van Rooyen','Caleb Windsor','Harvey Langford','Bayley Fritsch','Ed Langdon']},
    {id:'ade',name:'Adelaide',abbr:'ADE',color:'#002b5c',rank:7,players:['Jordan Dawson','Izak Rankine','Riley Thilthorpe','Josh Rachele','Jake Soligo','Darcy Fogarty','Max Michalanney','Daniel Curtin','Sid Draper','Mark Keane','Isaac Cumming','Ben Keays']},
    {id:'car',name:'Carlton',abbr:'CAR',color:'#071c3d',rank:10,players:['Patrick Cripps','Sam Walsh','Jacob Weitering','Harry McKay','Adam Cerra','George Hewett','Ben Ainsworth','Will Hayward','Oliver Florent','Blake Acres','Jagga Smith','Adam Saad']},
    {id:'col',name:'Collingwood',abbr:'COL',color:'#111111',rank:8,players:['Nick Daicos','Josh Daicos','Jordan De Goey','Darcy Moore','Dan Houston','Isaac Quaynor','Darcy Cameron','Beau McCreery','Lachie Schultz','Harry Perryman','Jack Crisp','Edward Allan']},
    {id:'wbd',name:'Western Bulldogs',abbr:'WBD',color:'#1b4f9c',rank:9,players:['Marcus Bontempelli','Sam Darcy','Ed Richards','Tim English','Aaron Naughton','Tom Liberatore','Ryley Sanders','Cody Weightman','Joel Freijah','Bailey Dale','Rhylee West','Rory Lobb']},
    {id:'haw',name:'Hawthorn',abbr:'HAW',color:'#4d2004',rank:4,players:['Jai Newcombe','Will Day','James Sicily','Nick Watson','Josh Weddle','Tom Barrass','Dylan Moore','Connor Macdonald','Massimo D\'Ambrosio','Lloyd Meek','Calsher Dear','Karl Amon']},
    {id:'stk',name:'St Kilda',abbr:'STK',color:'#ed1b2f',rank:11,players:['Nasiah Wanganeen-Milera','Jack Sinclair','Sam Flanders','Tom De Koning','Max King','Marcus Windhager','Mitch Owens','Mattaes Phillipou','Rowan Marshall','Jack Higgins','Callum Wilkie','Darcy Wilson']},
    {id:'gws',name:'GWS Giants',abbr:'GWS',color:'#f15a22',rank:12,players:['Tom Green','Finn Callaghan','Toby Greene','Sam Taylor','Lachie Whitfield','Josh Kelly','Jesse Hogan','Clayton Oliver','Kieren Briggs','Lachie Ash','Aaron Cadman','Brent Daniels']},
    {id:'gcs',name:'Gold Coast',abbr:'GCS',color:'#e7192d',rank:13,players:['Matt Rowell','Noah Anderson','Christian Petracca','Mac Andrew','Ben King','Daniel Rioli','Bailey Humphrey','Jed Walter','Touk Miller','Bodhi Uwland','John Noble','Ethan Read']},
    {id:'nm',name:'North Melbourne',abbr:'NM',color:'#00529b',rank:14,players:['Harry Sheezel','Luke Davies-Uniacke','Colby McKercher','George Wardlaw','Finn O\'Sullivan','Zane Duursma','Nick Larkey','Tristan Xerri','Caleb Daniel','Paul Curtis','Charlie Comben','Bailey Scott']},
    {id:'pa',name:'Port Adelaide',abbr:'PA',color:'#008aab',rank:15,players:['Zak Butters','Jason Horne-Francis','Connor Rozee','Miles Bergman','Mitch Georgiades','Jase Burgoyne','Aliir Aliir','Ollie Wines','Kane Farrell','Sam Powell-Pepper','Logan Evans','Willem Drew']},
    {id:'wce',name:'West Coast',abbr:'WCE',color:'#003087',rank:16,players:['Harley Reid','Willem Duursma','Reuben Ginbey','Jake Waterman','Liam Baker','Brandon Starcevich','Elijah Hewett','Bo Allan','Tim Kelly','Brady Hough','Archer Reid','Ryan Maric']},
    {id:'ess',name:'Essendon',abbr:'ESS',color:'#cc2031',rank:18,players:['Sam Durham','Zach Merrett','Jye Caldwell','Nate Caddy','Nic Martin','Jordan Ridley','Darcy Parish','Archie Roberts','Isaac Kako','Ben McKay','Xavier Duursma','Dyson Sharp']},
    {id:'ric',name:'Richmond',abbr:'RIC',color:'#f2d318',rank:17,clubText:'#111',players:['Sam Lalor','Josh Smillie','Tim Taranto','Ben Miller','Noah Balta','Taj Hotton','Jonty Faull','Tom Lynch','Jacob Hopper','Sam Grlj','Josh Gibcus','Kane McAuliffe']}
  ]
};
