(()=>{
const D=window.ATM_DATA,DD=window.ATM_DRAFT_DATA,$=s=>document.querySelector(s);if(!D||!DD)return;
const clubs=D.clubs,club=id=>clubs.find(c=>c.id===id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
const KEY='atm-draft-sandbox-v1';let history=[],future=[],sourceMeta=null;
function api(){return window.MockDraft}
function clone(x){return JSON.parse(JSON.stringify(x))}
function snap(label){const a=api();if(!a?.getState)return;history.push({label,state:clone(a.getState())});if(history.length>80)history.shift();future=[];renderToolbar();}
function restore(s){api()?.setState?.(clone(s));renderToolbar();}
function undo(){if(!history.length)return;const cur=clone(api().getState());const prev=history.pop();future.push({label:prev.label,state:cur});restore(prev.state);}
function redo(){if(!future.length)return;const cur=clone(api().getState());const next=future.pop();history.push({label:next.label,state:cur});restore(next.state);}
function modal(html){const m=$('#draftModal'),c=$('#draftModalCard');c.innerHTML=html;m.hidden=false;}
function close(){const m=$('#draftModal');m.hidden=true;$('#draftModalCard').innerHTML='';}
function options(sel=''){return clubs.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}" ${c.id===sel?'selected':''}>${esc(c.name)}</option>`).join('')}
function inject(){if($('#draftSandboxStyle'))return;const s=document.createElement('style');s.id='draftSandboxStyle';s.textContent=`
.draft-sandbox-bar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:0 0 14px}.draft-sandbox-bar .source-chip{margin-right:auto;padding:7px 10px;border-radius:999px;background:#f2f4f7;font-size:11px;font-weight:800;color:#384250}.draft-night-tabs{display:flex;gap:6px}.draft-night-tabs button.active{background:#171b24;color:#fff}.draft-row-actions{display:flex;gap:5px;flex-wrap:wrap}.draft-row-action{border:1px solid #d7dce3;background:#fff;border-radius:7px;padding:5px 7px;font-size:9px;font-weight:900;cursor:pointer}.draft-row-action:hover{border-color:#d71920;color:#d71920}.sandbox-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.sandbox-grid label{display:grid;gap:5px;font-size:11px;font-weight:900}.sandbox-wide{grid-column:1/-1}.night-divider{padding:9px 12px;background:#171b24;color:#fff;font-weight:900;font-size:11px;letter-spacing:.08em}.draft-order-row[data-night-hidden="true"]{display:none}.sandbox-note{font-size:12px;color:#667085}.clock-layout-fix .on-clock-row{display:grid!important;grid-template-columns:minmax(260px,.8fr) minmax(300px,1.2fr)!important}.clock-layout-fix .selected-prospect{height:auto!important;align-self:center!important}.clock-layout-fix{overflow:hidden!important}@media(max-width:760px){.sandbox-grid{grid-template-columns:1fr}.sandbox-wide{grid-column:auto}.clock-layout-fix .on-clock-row{grid-template-columns:1fr!important}}
`;document.head.appendChild(s);
const order=$('#draftOrder');order?.addEventListener('click',e=>{const b=e.target.closest('[data-sandbox-action]');if(!b)return;rowAction(b.dataset.sandboxAction,Number(b.dataset.pick));});
}
function nightFor(p){return p<=18?1:2}
function renderToolbar(){let bar=$('#draftSandboxBar');if(!bar){bar=document.createElement('div');bar.id='draftSandboxBar';bar.className='draft-sandbox-bar';$('#draftOrder')?.parentElement?.insertBefore(bar,$('#draftOrder'));}const src=sourceMeta?`Zero Hanger • ${new Date(sourceMeta.fetchedAt).toLocaleString('en-AU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}`:'Built-in baseline';bar.innerHTML=`<span class="source-chip">ORDER: ${esc(src)}</span><div class="draft-night-tabs"><button class="ghost-btn active" data-night="all">FULL DRAFT</button><button class="ghost-btn" data-night="1">NIGHT 1</button><button class="ghost-btn" data-night="2">NIGHT 2</button></div><button class="ghost-btn" id="liveOrderBtn">↻ LIVE ORDER</button><button class="ghost-btn" id="quickEditBtn">QUICK EDIT</button><button class="ghost-btn" id="compPickBtn">+ COMPO PICK</button><button class="ghost-btn" id="saveScenarioBtn">SAVE</button><button class="ghost-btn" id="loadScenarioBtn">LOAD</button><button class="ghost-btn" id="undoDraftBtn" ${history.length?'':'disabled'}>UNDO</button><button class="ghost-btn" id="redoDraftBtn" ${future.length?'':'disabled'}>REDO</button>`;
$('#liveOrderBtn').onclick=refreshLive;$('#quickEditBtn').onclick=()=>quickEdit();$('#compPickBtn').onclick=compPick;$('#saveScenarioBtn').onclick=saveScenario;$('#loadScenarioBtn').onclick=loadScenario;$('#undoDraftBtn').onclick=undo;$('#redoDraftBtn').onclick=redo;bar.querySelectorAll('[data-night]').forEach(b=>b.onclick=()=>filterNight(b.dataset.night,b));}
function decorateRows(){const rows=[...document.querySelectorAll('#draftOrder .draft-order-row')];rows.forEach(r=>{const pick=Number(r.querySelector('.draft-pick-no')?.textContent);if(!pick)return;if(r.querySelector('.draft-row-actions'))return;const box=document.createElement('div');box.className='draft-row-actions';box.innerHTML=`<button class="draft-row-action" data-sandbox-action="edit" data-pick="${pick}">EDIT</button><button class="draft-row-action" data-sandbox-action="trade" data-pick="${pick}">TRADE</button><button class="draft-row-action" data-sandbox-action="insert" data-pick="${pick}">+ PICK</button>`;r.appendChild(box);});const clock=document.querySelector('.club-themed-clock');clock?.classList.add('clock-layout-fix');}
function rowAction(a,p){if(a==='edit')quickEdit(p);if(a==='trade')tradePick(p);if(a==='insert')quickEdit(p,'insert');}
function quickEdit(pick=1,mode='edit'){const st=api().getState(),x=st.order.find(x=>x.pick===pick);modal(`<div class="modal-kicker">DRAFT SANDBOX</div><h3>${mode==='insert'?'Insert selection':'Edit Pick '+pick}</h3><p class="sandbox-note">Nothing after this pick is deleted. The board is recalculated around your change.</p><div class="sandbox-grid"><label>PICK<input id="sbPick" class="modal-select" type="number" min="1" value="${pick}"></label><label>OWNER<select id="sbOwner" class="modal-select">${options(x?.owner)}</select></label><label class="sandbox-wide">PLAYER<input id="sbPlayer" class="modal-select" list="sbProspects" value="${esc(x?.player?.name||'')}" placeholder="Leave blank for unselected"><datalist id="sbProspects">${DD.prospects.map(p=>`<option value="${esc(p.name)}">`).join('')}</datalist></label><label class="sandbox-wide">NOTE<input id="sbNote" class="modal-select" placeholder="Optional scenario note"></label></div><div class="modal-actions"><button class="ghost-btn" id="sbCancel">CANCEL</button>${mode==='edit'?'<button class="ghost-btn danger" id="sbDelete">DELETE PICK</button>':''}<button class="primary-btn" id="sbApply">APPLY</button></div>`);$('#sbCancel').onclick=close;if($('#sbDelete'))$('#sbDelete').onclick=()=>{snap('Delete pick');api().mutateOrder?.({type:'remove',pick});close();};$('#sbApply').onclick=()=>{snap(mode==='insert'?'Insert pick':'Edit pick');const np=Number($('#sbPick').value),owner=$('#sbOwner').value,name=$('#sbPlayer').value.trim(),note=$('#sbNote').value.trim();api().mutateOrder?.({type:mode==='insert'?'insert':'edit',pick:np,owner,playerName:name,note});close();};}
function tradePick(pick){const st=api().getState(),x=st.order.find(x=>x.pick===pick);if(!x)return;modal(`<div class="modal-kicker">QUICK DRAFT TRADE</div><h3>Trade Pick ${pick}</h3><p>${esc(club(x.owner)?.name)} → choose a new owner. Use the main Trade Machine for a full multi-asset trade, then import the resulting pick ownership here.</p><label class="modal-label">NEW OWNER</label><select id="sbTradeOwner" class="modal-select">${options(x.owner)}</select><label class="modal-label">TRADE NOTE</label><input id="sbTradeNote" class="modal-select" placeholder="e.g. Pick 12 + future R2"><div class="modal-actions"><button class="ghost-btn" id="sbCancel">CANCEL</button><button class="primary-btn" id="sbTrade">COMPLETE TRADE</button></div>`);$('#sbCancel').onclick=close;$('#sbTrade').onclick=()=>{snap('Trade pick');api().mutateOrder?.({type:'owner',pick,owner:$('#sbTradeOwner').value,note:$('#sbTradeNote').value});close();};}
function compPick(){modal(`<div class="modal-kicker">COMPENSATION / CONCESSION</div><h3>Add a pick</h3><p class="sandbox-note">Insert it exactly where it belongs. All later selections shift automatically, including Night 2.</p><div class="sandbox-grid"><label>INSERT AT PICK<input id="cpPick" class="modal-select" type="number" min="1" value="19"></label><label>CLUB<select id="cpOwner" class="modal-select">${options()}</select></label><label class="sandbox-wide">REASON<input id="cpNote" class="modal-select" value="Compensation pick"></label></div><div class="modal-actions"><button id="cpCancel" class="ghost-btn">CANCEL</button><button id="cpAdd" class="primary-btn">ADD PICK</button></div>`);$('#cpCancel').onclick=close;$('#cpAdd').onclick=()=>{snap('Add compensation pick');api().mutateOrder?.({type:'insert',pick:Number($('#cpPick').value),owner:$('#cpOwner').value,note:$('#cpNote').value});close();};}
async function refreshLive(){const btn=$('#liveOrderBtn');btn.disabled=true;btn.textContent='UPDATING…';try{const r=await fetch('/api/draft-order');const j=await r.json();if(!r.ok||!j.picks?.length)throw new Error(j.detail||'No live order');snap('Refresh live baseline');sourceMeta=j;api().applyBaseline?.(j.picks,{preserveSelections:true});renderToolbar();window.ATMToast?.(`Live order updated from Zero Hanger (${j.picks.length} picks)`);}catch(e){window.ATMToast?.(`Could not update live order: ${e.message}`);}finally{renderToolbar();}}
function syncTradeToDraft(){const tm=window.TradeMachine,a=api();if(!tm?.getTrade||!a?.getState||!a?.mutateOrder)return;const moves=tm.getTrade().filter(t=>t.asset?.type==='pick'&&t.asset?.year===2026&&Number.isFinite(Number(t.asset.pick)));if(!moves.length)return;const state=a.getState(),changes=moves.filter(t=>state.order.some(p=>Number(p.pick)===Number(t.asset.pick)&&p.owner!==t.to));if(!changes.length){window.ATMToast?.('Trade checked • live draft already reflects these pick owners');return;}snap('Run trade → live draft');for(const t of changes)a.mutateOrder({type:'owner',pick:Number(t.asset.pick),owner:t.to,note:`Trade Machine: ${club(t.from)?.abbr||t.from} → ${club(t.to)?.abbr||t.to}`});window.ATMToast?.(`${changes.length} traded 2026 pick${changes.length===1?'':'s'} updated in Live Draft Simulator`);}
function saveScenario(){const name=prompt('Scenario name?','My draft scenario');if(!name)return;const all=JSON.parse(localStorage.getItem(KEY)||'{}');all[name]={savedAt:new Date().toISOString(),sourceMeta,state:api().getState()};localStorage.setItem(KEY,JSON.stringify(all));window.ATMToast?.(`Saved “${name}”`);}
function loadScenario(){const all=JSON.parse(localStorage.getItem(KEY)||'{}'),names=Object.keys(all);if(!names.length)return window.ATMToast?.('No saved scenarios yet');modal(`<div class="modal-kicker">SAVED SCENARIOS</div><h3>Load a draft</h3><div class="scenario-change-list">${names.map(n=>`<button class="ghost-btn" data-load-scenario="${esc(n)}">${esc(n)} • ${new Date(all[n].savedAt).toLocaleString('en-AU')}</button>`).join('')}</div><div class="modal-actions"><button id="sbCancel" class="ghost-btn">CANCEL</button></div>`);$('#sbCancel').onclick=close;document.querySelectorAll('[data-load-scenario]').forEach(b=>b.onclick=()=>{snap('Load scenario');const v=all[b.dataset.loadScenario];sourceMeta=v.sourceMeta;restore(v.state);close();});}
function filterNight(n,btn){document.querySelectorAll('#draftSandboxBar [data-night]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('#draftOrder .draft-order-row').forEach(r=>{const p=Number(r.querySelector('.draft-pick-no')?.textContent),show=n==='all'||nightFor(p)===Number(n);r.dataset.nightHidden=String(!show);});}
function hook(){inject();renderToolbar();const obs=new MutationObserver(()=>decorateRows());const el=$('#draftOrder');if(el)obs.observe(el,{childList:true});decorateRows();$('#runTradeBtn')?.addEventListener('click',()=>setTimeout(syncTradeToDraft,0));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();