(() => {
  const DD = window.ATM_DRAFT_DATA;
  const D = window.ATM_DATA;
  if (!DD || !D) { console.error('Mock Draft data missing'); return; }

  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const profilePhoto=name=>window.ATM_PLAYER_PROFILES?.[window.ATM_MY_MOCK?.resolve?.(name)||name]?.photo||'assets/player-placeholder.svg';
  const prospectPhoto=(name,cls='prospect-photo')=>`<img class="${cls}" src="${esc(profilePhoto(name))}" onerror="this.src='assets/player-placeholder.svg'" alt="${esc(name)}">`;
  const clubs=[...D.clubs];
  const club=id=>clubs.find(c=>c.id===id);
  const CLUB_THEME={ade:{primary:'#f6c000',secondary:'#002b5c',text:'#fff'},bri:{primary:'#f5c400',secondary:'#7b002c',text:'#fff'},car:{primary:'#ffffff',secondary:'#071c3d',text:'#fff'},col:{primary:'#ffffff',secondary:'#111111',text:'#fff'},ess:{primary:'#d71920',secondary:'#050505',text:'#fff'},fre:{primary:'#ffffff',secondary:'#5b2b82',text:'#fff'},gee:{primary:'#ffffff',secondary:'#002b5c',text:'#fff'},gcs:{primary:'#ffd200',secondary:'#e7192d',text:'#fff'},gws:{primary:'#f15a22',secondary:'#202020',text:'#fff'},haw:{primary:'#f4c430',secondary:'#4d2004',text:'#fff'},mel:{primary:'#d71920',secondary:'#061a33',text:'#fff'},nm:{primary:'#ffffff',secondary:'#00529b',text:'#fff'},pa:{primary:'#00a2b8',secondary:'#111111',text:'#fff'},ric:{primary:'#f2d318',secondary:'#050505',text:'#fff'},stk:{primary:'#ed1b2f',secondary:'#111111',text:'#fff'},syd:{primary:'#e31b23',secondary:'#ffffff',text:'#fff'},wce:{primary:'#f4c430',secondary:'#003087',text:'#fff'},wbd:{primary:'#e31b23',secondary:'#1b4f9c',text:'#fff'}};
  const themeFor=id=>CLUB_THEME[id]||{primary:'#ddd',secondary:'#172337',text:'#fff'};
  const dvi=pick=>D.dvi?.[pick]??0;
  const toast=msg=>window.ATMToast?window.ATMToast(msg):console.log(msg);
  const currentLadder={fre:1,syd:2,bri:3,haw:4,gee:5,ade:6,mel:7,wbd:8,col:9,car:10,stk:11,gws:12,gcs:13,nm:14,pa:15,wce:16,ric:17,ess:18};
  let state,draggedProspectName=null;

  function baselineOrder(){return Object.entries(DD.ownerByPick).map(([pick,owner])=>({pick:Number(pick),owner,player:null,matched:false,custom:false})).sort((a,b)=>a.pick-b.pick);}
  function freshState(){return {order:baselineOrder(),selectedProspect:null,log:[],customChanges:[]};}
  function renumber(){state.order.sort((a,b)=>a.pick-b.pick).forEach((x,i)=>x.pick=i+1);}
  function recordChange(text){state.customChanges.push(text);addLog(`Custom order: ${text}`);}
  function reset(){state=freshState();render();toast('Draft reset to current baseline order');}
  function available(){const drafted=new Set(state.order.filter(x=>x.player).map(x=>x.player.name));return DD.prospects.filter(p=>!drafted.has(p.name));}
  function onClock(){return state.order.find(x=>!x.player);}
  function ladderPos(id){return currentLadder[id]||10;}
  function bidMultiplier(clubId,pick){const pos=ladderPos(clubId);if(pick>36)return 1;if(pick<=18&&pos<=2)return 1.20;if(pick<=18&&pos<=4)return 1.10;if(pos>=11)return .90;return 1;}
  function matchCost(clubId,pick){return Math.round(dvi(pick)*bidMultiplier(clubId,pick));}
  function clubLivePicks(id,afterPick){return state.order.filter(x=>!x.player&&x.owner===id&&x.pick>afterPick).sort((a,b)=>a.pick-b.pick);}
  function matchPlan(tiedClub,bidPick){const cost=matchCost(tiedClub,bidPick),eligible=clubLivePicks(tiedClub,bidPick),maxPicks=bidPick<=36?2:1,used=[];let points=0;for(const p of eligible){if(used.length>=maxPicks)break;used.push(p);points+=dvi(p.pick);if(points>=cost)break;}const deficit=Math.max(0,cost-points),hasFutureFirst=(D.picks2027?.[tiedClub]||[]).some(([round])=>round===1);return {cost,used,points,deficit,hasFutureFirst,canMatch:deficit===0||(deficit<=DD.deficitCap&&hasFutureFirst)};}
  function addLog(text){state.log.unshift({time:new Date().toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit'}),text});}
  function openModal(html){const modal=$('#draftModal'),card=$('#draftModalCard');if(!modal||!card)return;card.innerHTML=html;modal.hidden=false;}
  function closeModal(){const modal=$('#draftModal'),card=$('#draftModalCard');if(modal)modal.hidden=true;if(card)card.innerHTML='';}

  function installStyles(){if($('#draftScenarioStyles'))return;const s=document.createElement('style');s.id='draftScenarioStyles';s.textContent=`
    .club-themed-clock{background:linear-gradient(135deg,var(--teamSecondary) 0%,var(--teamSecondary) 62%,color-mix(in srgb,var(--teamPrimary) 38%,var(--teamSecondary)) 100%)!important;color:#fff!important;border:1px solid color-mix(in srgb,var(--teamPrimary) 65%,transparent);border-radius:18px;padding:22px!important;min-height:0!important;box-shadow:0 18px 45px rgba(0,0,0,.22)}
    .club-themed-clock .on-clock-row{align-items:center;gap:20px}.club-themed-clock .on-clock-label,.club-themed-clock .on-clock-pick,.club-themed-clock h2,.club-themed-clock .on-clock-meta,.club-themed-clock .draft-drop-copy{color:#fff!important}.club-themed-clock .selected-prospect{background:rgba(0,0,0,.25)!important;border:1px solid rgba(255,255,255,.18)!important;color:#fff!important;border-radius:14px!important;padding:16px!important;min-height:0!important}.club-themed-clock .selected-prospect strong,.club-themed-clock .selected-prospect span,.club-themed-clock .selected-prospect small{color:#fff!important}.club-themed-clock .selected-prospect-card{background:transparent!important}.clock-club-name img{max-height:58px}.draft-custom-badge,.custom-status{display:inline-flex;align-items:center;border-radius:999px;font-size:10px;font-weight:900;letter-spacing:.08em;padding:4px 8px;background:#f3c83b;color:#171717}.custom-status{margin-top:10px}.draft-edit-btn{border:1px solid rgba(255,255,255,.2);background:transparent;color:inherit;border-radius:7px;padding:5px 8px;font-size:10px;font-weight:800;cursor:pointer}.draft-edit-btn:hover{background:rgba(255,255,255,.1)}.scenario-change-list{display:grid;gap:7px;margin:12px 0}.scenario-change-list div{padding:9px 11px;border-radius:8px;background:rgba(127,127,127,.12);font-size:12px}.scenario-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.scenario-grid label{display:grid;gap:6px}.scenario-grid label span{font-size:11px;font-weight:800;letter-spacing:.06em}.scenario-wide{grid-column:1/-1}@media(max-width:700px){.scenario-grid{grid-template-columns:1fr}.club-themed-clock .on-clock-row{gap:12px}.club-themed-clock{padding:16px!important}}
  `;document.head.appendChild(s);}
  function ensureScenarioButton(){if($('#customiseDraftOrderBtn'))return;const anchor=$('#draftTradePickBtn')||$('#resetDraftBtn');if(!anchor)return;const b=document.createElement('button');b.id='customiseDraftOrderBtn';b.className='ghost-btn';b.textContent='CUSTOMISE ORDER';b.onclick=openScenarioManager;anchor.parentNode.insertBefore(b,anchor);}

  function openScenarioManager(){const options=clubs.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');openModal(`<div class="modal-kicker">SCENARIO LAYER</div><h3>Customise the draft order</h3><p>The baseline stays as the current published indicative order. Your hypothetical changes sit on top and are marked <strong>CUSTOM</strong>.</p><div class="scenario-grid"><label><span>ACTION</span><select id="scenarioAction" class="modal-select"><option value="insert">Insert a new pick</option><option value="owner">Change pick owner</option><option value="remove">Remove a pick</option></select></label><label><span>PICK NUMBER</span><input id="scenarioPick" class="modal-select" type="number" min="1" max="100" value="6"></label><label id="scenarioClubWrap"><span>CLUB</span><select id="scenarioClub" class="modal-select">${options}</select></label><label class="scenario-wide"><span>NOTE (OPTIONAL)</span><input id="scenarioNote" class="modal-select" placeholder="e.g. Ben King compensation assumption"></label></div>${state.customChanges.length?`<div class="scenario-change-list">${state.customChanges.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}<div class="modal-actions"><button id="scenarioReset" class="ghost-btn">RESET TO BASELINE</button><button id="scenarioCancel" class="ghost-btn">CANCEL</button><button id="scenarioApply" class="primary-btn">APPLY CHANGE</button></div>`);const action=$('#scenarioAction'),wrap=$('#scenarioClubWrap');action.onchange=()=>wrap.style.display=action.value==='remove'?'none':'grid';$('#scenarioCancel').onclick=closeModal;$('#scenarioReset').onclick=()=>{closeModal();reset();};$('#scenarioApply').onclick=applyScenarioChange;}
  function applyScenarioChange(){const action=$('#scenarioAction').value,pick=Math.max(1,Number($('#scenarioPick').value)||1),owner=$('#scenarioClub').value,note=$('#scenarioNote').value.trim(),suffix=note?` — ${note}`:'';if(action==='insert'){state.order.forEach(x=>{if(x.pick>=pick)x.pick++;});state.order.push({pick,owner,player:null,matched:false,custom:true});recordChange(`Inserted ${club(owner).name} at Pick ${pick}${suffix}`);}else if(action==='owner'){const item=state.order.find(x=>x.pick===pick);if(!item)return toast(`Pick ${pick} does not exist`);const from=item.owner;item.owner=owner;item.custom=true;recordChange(`Pick ${pick}: ${club(from).name} → ${club(owner).name}${suffix}`);}else{const idx=state.order.findIndex(x=>x.pick===pick);if(idx<0)return toast(`Pick ${pick} does not exist`);const [removed]=state.order.splice(idx,1);renumber();recordChange(`Removed Pick ${pick} (${club(removed.owner)?.name||removed.owner})${suffix}`);}state.order.sort((a,b)=>a.pick-b.pick);closeModal();render();}

  function reopenPick(pick){const item=state.order.find(x=>x.pick===pick);if(!item?.player)return;if(item.matched){toast('Matched bids need to be undone as a bid transaction; simple edit is disabled for this pick.');return;}const name=item.player.name;item.player=null;state.selectedProspect=null;addLog(`Pick ${pick} reopened. ${name} returned to the prospect pool.`);render();document.querySelector('.on-clock-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}
  function selectProspect(name){state.selectedProspect=DD.prospects.find(p=>p.name===name)||null;renderOnClock();renderProspects();document.querySelector('.on-clock-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}
  function usePick(){const oc=onClock(),prospect=state.selectedProspect;if(!oc)return toast('Draft complete');if(!prospect)return toast('Select a prospect first');if(prospect.tiedClub&&prospect.tiedClub!==oc.owner)return handleBid(oc,prospect);oc.player=prospect;addLog(`Pick ${oc.pick}: ${club(oc.owner).name} selects ${prospect.name}.`);state.selectedProspect=null;render();}
  function handleBid(oc,prospect){const tiedClub=club(prospect.tiedClub),plan=matchPlan(prospect.tiedClub,oc.pick);openModal(`<div class="modal-kicker">CLUB-TIED BID</div><h3>Pick ${oc.pick}: ${esc(club(oc.owner).name)} bids on ${esc(prospect.name)}</h3><p>${esc(prospect.tieType)} prospect tied to <strong>${esc(tiedClub.name)}</strong>.</p><div class="bid-grid"><div><span>Bid value</span><strong>${dvi(oc.pick).toLocaleString()} pts</strong></div><div><span>Adjusted match cost</span><strong>${plan.cost.toLocaleString()} pts</strong></div><div><span>Picks used</span><strong>${plan.used.map(p=>p.pick).join(', ')||'None'}</strong></div><div><span>Deficit</span><strong>${plan.deficit.toLocaleString()} pts${plan.deficit?` • ${plan.hasFutureFirst?'future R1 held':'NO future R1'}`:''}</strong></div></div><p class="modal-note">Core 2026 match rules are represented. Complex surplus-pick and compensation reshuffling remains an MVP approximation.</p><div class="modal-actions"><button class="ghost-btn" id="declineBidBtn">DECLINE MATCH</button><button class="primary-btn" id="matchBidBtn" ${plan.canMatch?'':'disabled'}>MATCH BID</button></div>`);$('#declineBidBtn').onclick=()=>{oc.player=prospect;addLog(`Pick ${oc.pick}: ${club(oc.owner).name} bids on ${prospect.name}; ${tiedClub.name} declines.`);state.selectedProspect=null;closeModal();render();};$('#matchBidBtn').onclick=()=>matchBid(oc,prospect,plan);}
  function matchBid(oc,prospect,plan){const tied=prospect.tiedClub,bidPick=oc.pick,consumed=new Set(plan.used),remaining=state.order.filter(item=>!consumed.has(item));remaining.filter(x=>x.pick>=bidPick).forEach(x=>x.pick++);remaining.push({pick:bidPick,owner:tied,player:prospect,matched:true,custom:false});state.order=remaining.sort((a,b)=>a.pick-b.pick);renumber();addLog(`${club(tied).name} matches the bid on ${prospect.name}${plan.deficit>0?`; ${plan.deficit} points carried as an indicative future deficit`:` using picks ${plan.used.map(p=>p.pick).join(' and ')}`}.`);state.selectedProspect=null;closeModal();render();}
  function tradeOnClock(){const oc=onClock();if(!oc)return toast('Draft complete');const others=clubs.filter(c=>c.id!==oc.owner).sort((a,b)=>a.name.localeCompare(b.name));openModal(`<div class="modal-kicker">LIVE PICK TRADE</div><h3>Trade Pick ${oc.pick}</h3><p><strong>${esc(club(oc.owner).name)}</strong> currently owns the on-clock selection.</p><label class="modal-label">TRADE PICK TO</label><select id="draftTradeDest" class="modal-select">${others.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><div class="modal-actions"><button id="cancelDraftTrade" class="ghost-btn">CANCEL</button><button id="confirmDraftTrade" class="primary-btn">TRADE PICK</button></div>`);$('#cancelDraftTrade').onclick=closeModal;$('#confirmDraftTrade').onclick=()=>{const from=oc.owner,to=$('#draftTradeDest').value;oc.owner=to;oc.custom=true;recordChange(`Live trade: Pick ${oc.pick}, ${club(from).name} → ${club(to).name}`);closeModal();render();};}

  function renderOnClock(){const el=$('#onClock');if(!el)return;const oc=onClock();if(!oc){el.innerHTML='<div class="on-clock-inner"><div class="on-clock-label">DRAFT COMPLETE</div><h2>Every available selection has been used.</h2></div>';return;}const p=state.selectedProspect,c=club(oc.owner),t=themeFor(oc.owner);el.innerHTML=`<div class="on-clock-inner club-themed-clock draft-drop-target" style="--teamPrimary:${t.primary};--teamSecondary:${t.secondary};--teamText:${t.text}"><div class="on-clock-label">ON THE CLOCK</div><div class="on-clock-row"><div><div class="on-clock-pick">PICK ${oc.pick}</div><div class="clock-club-name"><img src="${esc(c.logo)}" alt=""><h2>${esc(c.name)}</h2></div><div class="on-clock-meta">${dvi(oc.pick).toLocaleString()} DVI points • current owner</div>${state.customChanges.length?`<div class="custom-status">CUSTOM SCENARIO • ${state.customChanges.length} CHANGE${state.customChanges.length===1?'':'S'}</div>`:''}<div class="draft-drop-copy">DRAG A PROSPECT HERE TO SELECT</div></div><div class="selected-prospect">${p?`<span>Selected prospect</span><div class="selected-prospect-card">${prospectPhoto(p.name,'selected-prospect-photo')}<div><button class="selected-profile-name" id="selectedProfileBtn">${esc(p.name)}</button><small>${esc(p.position)} • ${esc(p.pathway)}${p.tiedClub?` • ${esc(p.tieType)}: ${esc(club(p.tiedClub).abbr)}`:''}</small></div></div><button id="draftPlayerBtn" class="primary-btn">USE PICK ${oc.pick}</button>`:'<span>NO PROSPECT SELECTED</span><strong>Choose or drag a player from the prospect board</strong><small>Drop a prospect on this card, or drag directly to the current pick.</small>'}</div></div></div>`;if(p){$('#draftPlayerBtn').onclick=usePick;$('#selectedProfileBtn').onclick=()=>window.ATMProfiles?.open?.(p.name,{clubId:oc.owner,pick:oc.pick});}const target=el.querySelector('.draft-drop-target');target.ondragover=e=>{if(!draggedProspectName)return;e.preventDefault();target.classList.add('drag-over');};target.ondragleave=e=>{if(!target.contains(e.relatedTarget))target.classList.remove('drag-over');};target.ondrop=e=>{e.preventDefault();target.classList.remove('drag-over');if(draggedProspectName)selectProspect(draggedProspectName);};}
  function renderOrder(){const el=$('#draftOrder');if(!el)return;const oc=onClock();el.innerHTML=state.order.map(x=>{const c=club(x.owner);return `<div class="draft-order-row ${x===oc?'current draft-pick-drop-target':''} ${x.player?'used':''}" ${x===oc?'data-current-pick="true"':''}><div class="draft-pick-no">${x.pick}</div><div class="draft-club-logo"><img src="${esc(c?.logo||'')}" alt=""></div><div class="draft-club"><strong>${esc(c?.abbr||x.owner)}</strong><span>${esc(c?.name||'')}</span>${x.custom?'<em class="draft-custom-badge">CUSTOM</em>':''}</div><div class="draft-points">${dvi(x.pick).toLocaleString()} pts</div><div class="draft-player">${x.player?`<div class="draft-player-with-photo">${prospectPhoto(x.player.name,'draft-picked-photo')}<span><strong>${esc(x.player.name)}</strong><small>${esc(x.player.position)}</small></span></div>`:x===oc?'<span class="pick-drop-copy">DROP PROSPECT TO USE PICK</span>':'—'}</div>${x.player&&!x.matched?`<button class="draft-edit-btn" data-edit-pick="${x.pick}">EDIT PICK</button>`:''}${x.matched?'<span class="matched-badge">MATCHED BID</span>':''}</div>`}).join('');el.querySelectorAll('[data-edit-pick]').forEach(b=>b.onclick=()=>reopenPick(Number(b.dataset.editPick)));const current=el.querySelector('[data-current-pick="true"]');if(current){current.ondragover=e=>{if(!draggedProspectName)return;e.preventDefault();current.classList.add('drag-over');};current.ondragleave=e=>{if(!current.contains(e.relatedTarget))current.classList.remove('drag-over');};current.ondrop=e=>{e.preventDefault();current.classList.remove('drag-over');const name=draggedProspectName;if(!name)return;state.selectedProspect=DD.prospects.find(p=>p.name===name)||null;draggedProspectName=null;usePick();};}}
  function renderProspects(){const el=$('#prospectBoard');if(!el)return;const q=($('#prospectSearch')?.value||'').toLowerCase().trim(),list=available().filter(p=>(`${p.name} ${p.position} ${p.pathway} ${p.tieType||''}`).toLowerCase().includes(q));el.innerHTML=list.map(p=>`<div class="prospect-row ${state.selectedProspect?.name===p.name?'selected':''}" data-drag-prospect="${esc(p.name)}" draggable="true"><span class="prospect-rank">${p.rank}</span>${prospectPhoto(p.name)}<span class="prospect-copy"><button class="prospect-name-link" data-profile-name="${esc(p.name)}">${esc(p.name)}</button><small>${esc(p.position)} • ${esc(p.pathway)}</small>${p.tiedClub?`<em>${esc(p.tieType)} • ${esc(club(p.tiedClub).name)}</em>`:''}</span><span class="prospect-actions-inline"><button class="prospect-profile-label" data-profile-name="${esc(p.name)}">PROFILE</button><button class="prospect-select-label" data-prospect="${esc(p.name)}">SELECT</button></span></div>`).join('');el.querySelectorAll('[data-prospect]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectProspect(b.dataset.prospect);});el.querySelectorAll('[data-profile-name]').forEach(b=>b.onclick=e=>{e.stopPropagation();const oc=onClock();window.ATMProfiles?.open?.(b.dataset.profileName,{clubId:oc?.owner||null,pick:oc?.pick||null});});el.querySelectorAll('[data-drag-prospect]').forEach(row=>{const name=row.dataset.dragProspect;row.onclick=e=>{if(e.target.closest('button'))return;selectProspect(name);};row.ondragstart=e=>{draggedProspectName=name;e.dataTransfer.effectAllowed='copyMove';e.dataTransfer.setData('text/plain',name);requestAnimationFrame(()=>row.classList.add('dragging'));};row.ondragend=()=>{draggedProspectName=null;document.querySelectorAll('.dragging,.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'));};});}
  function compareWithMyMock(){const mock=(window.ATM_MY_MOCK?.board||[]).filter(r=>!r.placeholder).slice(0,40);if(!mock.length)return toast('My Mock Draft is unavailable');const live=state.order.slice().sort((a,b)=>a.pick-b.pick).slice(0,40),rows=Array.from({length:40},(_,i)=>{const pick=i+1,l=live.find(x=>x.pick===pick),m=mock.find(x=>Number(x.pick)===pick),liveName=l?.player?.name||'',mockName=m?.player||'',same=liveName&&mockName&&liveName===mockName,lc=l?club(l.owner):null,mc=m?club(m.clubId):null;return `<div class="current-compare-row ${same?'same':liveName?'different':'pending'}"><span class="compare-pick">${pick}</span><div class="compare-live"><span><strong>${liveName?esc(liveName):'—'}</strong><small>${esc(lc?.abbr||'')}</small></span></div><div class="compare-status"><strong>${same?'MATCH':liveName?'DIFFERENT':'PENDING'}</strong></div><div class="compare-mock"><span><strong>${esc(mockName||'—')}</strong><small>${esc(mc?.abbr||'')}</small></span></div></div>`;}).join(''),selected=live.filter(x=>x.player).length,exact=live.filter(x=>x.player&&mock.find(m=>Number(m.pick)===x.pick)?.player===x.player.name).length;openModal(`<div class="modal-kicker">2026 DRAFT COMPARISON</div><h3>Live Simulator vs My Mock Draft</h3><div class="current-compare-summary"><div><span>LIVE PICKS MADE</span><strong>${selected}</strong></div><div><span>EXACT MATCHES</span><strong>${exact}</strong></div><div><span>DIFFERENCES</span><strong>${Math.max(0,selected-exact)}</strong></div></div><div class="current-compare-list">${rows}</div><div class="modal-actions"><button id="closeCurrentCompare" class="primary-btn">CLOSE</button></div>`);$('#closeCurrentCompare').onclick=closeModal;}
  function renderLog(){const el=$('#draftLog');if(!el)return;el.innerHTML=state.log.length?state.log.map(l=>`<div class="log-item"><span>${esc(l.time)}</span><p>${esc(l.text)}</p></div>`).join(''):'<div class="empty-log">Selections, club-tied bids, live pick trades and custom scenarios will appear here.</div>';}
  function render(){ensureScenarioButton();renderOnClock();renderOrder();renderProspects();renderLog();}
  function init(){state=freshState();installStyles();ensureScenarioButton();if($('#prospectSearch'))$('#prospectSearch').oninput=renderProspects;if($('#resetDraftBtn'))$('#resetDraftBtn').onclick=reset;if($('#draftTradePickBtn'))$('#draftTradePickBtn').onclick=tradeOnClock;if($('#compareCurrentDraftBtn'))$('#compareCurrentDraftBtn').onclick=compareWithMyMock;if($('#draftModal'))$('#draftModal').onclick=e=>{if(e.target.id==='draftModal')closeModal();};render();}
  function getState(){return state;}
function setState(next){state=next;render();}
function findProspect(name){return DD.prospects.find(p=>p.name===name)||null;}
function mutateOrder(change){
  if(change.type==='insert'){
    state.order.forEach(x=>{if(x.pick>=change.pick)x.pick++;});
    state.order.push({pick:change.pick,owner:change.owner,player:change.playerName?findProspect(change.playerName):null,matched:false,custom:true});
  }else if(change.type==='remove'){
    state.order=state.order.filter(x=>x.pick!==change.pick);renumber();
  }else if(change.type==='owner'){
    const x=state.order.find(x=>x.pick===change.pick);if(x){x.owner=change.owner;x.custom=true;}
  }else if(change.type==='edit'){
    const x=state.order.find(x=>x.pick===change.pick);if(x){x.owner=change.owner;x.player=change.playerName?findProspect(change.playerName):null;x.custom=true;}
  }
  if(change.note)recordChange(change.note);state.order.sort((a,b)=>a.pick-b.pick);render();
}
function applyBaseline(picks,opts={}){
  const old=state.order, byPick=new Map(old.map(x=>[x.pick,x]));
  state.order=picks.map(p=>{const prev=byPick.get(p.pick);return {pick:p.pick,owner:p.owner,player:opts.preserveSelections?prev?.player||null:null,matched:opts.preserveSelections?prev?.matched||false:false,custom:false};});
  state.customChanges=[];addLog('Baseline refreshed from live published draft order.');render();
}
window.MockDraft={render,reset,compareWithMyMock,reopenPick,openScenarioManager,getState,setState,mutateOrder,applyBaseline};
  init();
})();